### ISSUE TITLE
Consider moving the react dependency to `devDependencies`

### ISSUE THREAD

**Issue by 0gust1** [CAYdenberg/node-ncbi#20]
Thanks a lot for this very useful package!

We currently use on our backend side, and I noticed recently that a lot of dependencies were added to our project when building and deploying, and found out it was because of node-ncbi.

Could you consider moving the dependencies that are not mandatory to package use into `devDependencies` of your `package.json` file ?

If it helps, I can make a Pull Request.

Thanks again and have a nice day!

**Comment by CAYdenberg** [comment]
Released in 0.7.1

**Comment by CAYdenberg** [comment]
... also I just added a typescript declaration file in 0.7.2. Let me know if this improves things for you :)
